[package]
name = "devicemapper"
version = "0.32.1"
authors = ["Stratis Developers <stratis-devel@lists.fedorahosted.org>"]
description = "A library for using Linux device mapper"
documentation = "https://docs.rs/devicemapper/"
repository = "https://github.com/stratis-storage/devicemapper-rs"
readme = "README.md"
categories = ["os::linux-apis", "api-bindings"]
keywords = ["Linux", "device", "mapper", "libdm", "storage"]
license = "MPL-2.0"
edition = "2018"
exclude = [".gitignore", ".github/*", "Makefile"]

[dependencies]
bitflags = "1.1.0"
env_logger="0.9.0"
nix = "0.24.0"
semver = "1.0.0"
serde = "1.0.60"
lazy_static = "1.2.0"
log = "0.4.14"

[dev-dependencies]
libmount = "0.1.11"
libudev = "0.2.0"
loopdev = "0.2.0"
matches = "0.1.8"
tempfile = "3.0.2"

[dev-dependencies.uuid]
version = "1.0.0"
features = ["v4"]

[dependencies.devicemapper-sys]
version = "0.1.0"
path = "./devicemapper-rs-sys"

[build-dependencies.devicemapper-sys]
version = "0.1.0"
path = "./devicemapper-rs-sys"

[build-dependencies]
semver = "1.0.0"
